### Pytorch Tutorial
#### Tensors Basics
A tensor is a generalization of vectors and matrices and is easily understood as a multidimensional array.It is a term and set of techniques known in machine learning in the training and operation of deep learning models can be described in terms of tensors.
In many cases tensors are used as a replacement for NumPy to use the power of GPUs.

Tensors are a type of data structure used in linear algebra, and like vectors and matrices, you can calculate arithmetic operations with tensors.

In [56]:
import torch

In [57]:
torch.__version__

'1.5.1'

In [58]:
import numpy as np

In [59]:
lst=[3,4,5,6]
arr=np.array(lst)

In [61]:
arr

array([3, 4, 5, 6])

In [60]:
arr.dtype

dtype('int32')

### Convert Numpy To Pytorch Tensors

In [62]:
tensors=torch.from_numpy(arr)
tensors

tensor([3, 4, 5, 6], dtype=torch.int32)

In [64]:
### Indexing similar to numpy
tensors[2]


tensor(5, dtype=torch.int32)

In [27]:
tensors[1:4]

tensor([4, 5, 6], dtype=torch.int32)

In [65]:
#### Disadvantage of from_numpy. The array and tensor uses the same memory location
tensors[3]=100

In [66]:
tensors

tensor([  3,   4,   5, 100], dtype=torch.int32)

In [67]:
arr

array([  3,   4,   5, 100])

In [68]:
### Prevent this by using torch.tensor
tensor_arr=torch.tensor(arr)
tensor_arr

tensor([  3,   4,   5, 100], dtype=torch.int32)

In [69]:
tensor_arr[3]=120
print(tensor_arr)
print(arr)

tensor([  3,   4,   5, 120], dtype=torch.int32)
[  3   4   5 100]


In [70]:
##zeros and ones
torch.zeros(2,3,dtype=torch.float64)

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [37]:
torch.ones(2,3,dtype=torch.float64)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [73]:
a=torch.tensor(np.arange(0,15).reshape(5,3))

In [76]:
a[:,0:2]

tensor([[ 0,  1],
        [ 3,  4],
        [ 6,  7],
        [ 9, 10],
        [12, 13]], dtype=torch.int32)

##### Arithmetic Operation

In [79]:
a = torch.tensor([3,4,5], dtype=torch.float)
b = torch.tensor([4,5,6], dtype=torch.float)
print(a + b)

tensor([ 7.,  9., 11.])


In [80]:
torch.add(a,b)

tensor([ 7.,  9., 11.])

In [81]:
c=torch.zeros(3)

In [82]:
torch.add(a,b,out=c)

tensor([ 7.,  9., 11.])

In [83]:
c

tensor([ 7.,  9., 11.])

In [44]:
##### Some more operations
a = torch.tensor([3,4,5], dtype=torch.float)
b = torch.tensor([4,5,6], dtype=torch.float)

In [84]:
### tensor[7,9,15]
torch.add(a,b).sum()

tensor(27.)

##### Dot Products and Mult Operations

In [46]:
x= torch.tensor([3,4,5], dtype=torch.float)
y = torch.tensor([4,5,6], dtype=torch.float)

In [47]:
x.mul(y)

tensor([12., 20., 30.])

In [49]:
### 3*4+5*4+6*5

In [48]:
x.dot(y)

tensor(62.)

In [50]:
###### MAtrix Multiplication

In [51]:
x = torch.tensor([[1,4,2],[1,5,5]], dtype=torch.float)
y = torch.tensor([[5,7],[8,6],[9,11]], dtype=torch.float)

In [52]:
torch.matmul(x,y)

tensor([[55., 53.],
        [90., 92.]])

In [54]:
torch.mm(x,y)

tensor([[55., 53.],
        [90., 92.]])

In [55]:
x@y

tensor([[55., 53.],
        [90., 92.]])